# Generated by Django 4.2.5 on 2024-02-22 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('languages', models.CharField(blank=True, max_length=256)),
                ('programming_languages', models.CharField(blank=True, max_length=256)),
                ('education', models.TextField(blank=True)),
                ('stack', models.CharField(blank=True, max_length=50)),
                ('about', models.TextField(blank=True)),
                ('age', models.PositiveIntegerField(blank=True, default=18)),
                ('work_experience', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about_company', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('direction', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='company/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
