version: "3"
services:
  redux-postgres:
    image: postgres
    container_name: redux-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    container_name: goszap
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/back-static
      - media_volume:/usr/src/app/back-media
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application"
    depends_on:
      - redux-postgres
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: redux-postgres  

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx_ssl/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/app/back-static
      - media_volume:/usr/src/app/back-media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
  db_data:
